name             'insight'
maintainer       'Philip Hutchins'
maintainer_email 'flipture@gmail.com'
license          'BSD'
description      'Installs/Configures chef-insight'
long_description 'Installs/Configures chef-insight'
version          '0.2.9'

depends 'nvm'
depends 'chef-bitcoind'
depends 'nginx'
